services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=172.17.0.1  # This is the key trick on Windows/macOS
      - DB_NAME=cicd_test
      - DB_USER=postgres
      - DB_PASSWORD=admin
    depends_on: []
